/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package workout_builder_gradle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import com.garmin.fit.WktStepDuration;
import com.garmin.fit.WorkoutStepMesg;

class WorkoutStepTest {
    @Test
    void workoutStepDurationTimeInputIsTime() {
        WorkoutStepMesg step = WorkoutStep.buildStep(1, "Warmup", "Time", 1200000, "Watts", 300, "130bpm", null);
        WktStepDuration duration_type = step.getDurationType();
        assertTrue(duration_type instanceof WktStepDuration, "WorkoutStep should return a WktStepDuration type");
        assertTrue(duration_type.getValue() == (short) 0, "WorkoutStep should return value of 0");

    }

    @Test
    void workoutStepDurationTimeInputIsDistance() {
        WorkoutStepMesg step = WorkoutStep.buildStep(1, "Warmup", "Distance", 1200000, "Watts", 300, "130bpm", null);
        WktStepDuration duration_type = step.getDurationType();
        assertTrue(duration_type instanceof WktStepDuration, "WorkoutStep should return a WktStepDuration type");
        assertTrue(duration_type.getValue() == (short) 1, "WorkoutStep should return value of 1");

    }

    @Test
    void workoutStepDurationTimeInputIsOpen() {
        WorkoutStepMesg step = WorkoutStep.buildStep(1, "Warmup", "Open", 1200000, "Watts", 300, "130bpm", null);
        WktStepDuration duration_type = step.getDurationType();
        assertTrue(duration_type instanceof WktStepDuration, "WorkoutStep should return a WktStepDuration type");
        assertTrue(duration_type.getValue() == (short) 5, "WorkoutStep should return value of 5");

    }

    @Test
    void workoutStepDurationTimeInputIsUnknown() {
        WorkoutStepMesg step = WorkoutStep.buildStep(1, "Warmup", "whatever", 1200000, "Watts", 300, "130bpm", null);
        assertTrue(step == null, "WorkoutStep should return null");
    }
}
